name: CopyAI Generate draft

on: 
  repository_dispatch:
    types: [copyai-draft] #Manual triggered from Coda

env:
  ORG_NAME: ${{ vars.ORG_NAME }}
  CB: ${{ vars.CB }}
  CTB: ${{ vars.CTB }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'       
      - name: Install requirements
        run: sudo pip install -r .github/workflows/copyai/requirements.txt #Where to put scripts?
