name: CopyAI Generate draft

on: 
  repository_dispatch:
    types: [copyai-draft] #Manual triggered from Coda

env:
  ORG_NAME: ${{ vars.ORG_NAME }}
  CB: ${{ vars.CB }}
  CTB: ${{ vars.CTB }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
  COPYAI_API_KEY: ${{ secrets.COPYAI_API_KEY }}        
  COPYAI_WF_ID: ${{ vars.COPYAI_WF_ID }}        

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  
      - name: Get upstream meta data
        run: |
          mkdir tmp
          cd tmp
          wget https://raw.githubusercontent.com/$ORG_NAME/$CB/main/README.md
          mv README.md ../cb.txt
          wget https://raw.githubusercontent.com/$ORG_NAME/$CTB/main/README.md
          mv README.md ../ctb.txt
          cd ..
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'               
      - name: Create venv
        run: |
          python3 -m venv copyai
          source copyai/bin/activate
      - name: Install requirements
        run: sudo pip install -r .github/copyai/requirements.txt #Where to put scripts?          
      - name: Create draft content with CopyAI
        run: |
          source copyai/bin/activate
          cp .github/copyai/copyai.py .
          python3 copyai.py
      - name: Setup git config
        run: |
          git config --global user.email your-email@users.noreply.github.com
          git config --global user.name 'Pipeline'             
      - name: Submit draft to repository
        run: |
          git add output.md
          git commit -m "Add CopyAI draft."
          git push                          

        