name: Check for upstream changes
on:
  schedule:
    - cron: "* */5 * * *"
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: JasonEtco/create-an-issue@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/tme-test-org/tme-cb-1/releases/releases/latest | \
          jq -r ".tag_name" > test.txt
      # - name: Check for modified files
      #   id: git-check
      #   run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        # if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-email@users.noreply.github.com'
          git commit -am "New release version"
          git push

