name: Releases

on: 
  repository_dispatch:
    types: [release] #Manual triggered from Coda

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Release
        uses: huggingface/semver-release-action@latest