name: Releases

on: 
  repository_dispatch:
    types: [release] #Manual triggered from Coda

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: avakar/tag-and-release@v1
      with:
        tag_name: "test"
